### ISSUE TITLE
setup so we can publish this as snapshot to our repo.9ci

### ISSUE THREAD

**Issue by basejump** [yakworks/build-test-data#1]

**Comment by snimavat** [comment]
@basejump just like our other plugins

Add 
artifactoryUsername=xx
artifactoryPassword=xx

to ~/.gradle/gradle.properties

And thn do, gradle build-test-data:publush -- it will publish snapshot to 9ci artifacory

**Comment by snimavat** [comment]
@basejump have a look at PR
